require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AcompanhamentosController do

  # This should return the minimal set of attributes required to create a valid
  # Acompanhamento. As you add validations to Acompanhamento, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "contratos" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AcompanhamentosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all acompanhamentos as @acompanhamentos" do
      acompanhamento = Acompanhamento.create! valid_attributes
      get :index, {}, valid_session
      assigns(:acompanhamentos).should eq([acompanhamento])
    end
  end

  describe "GET show" do
    it "assigns the requested acompanhamento as @acompanhamento" do
      acompanhamento = Acompanhamento.create! valid_attributes
      get :show, {:id => acompanhamento.to_param}, valid_session
      assigns(:acompanhamento).should eq(acompanhamento)
    end
  end

  describe "GET new" do
    it "assigns a new acompanhamento as @acompanhamento" do
      get :new, {}, valid_session
      assigns(:acompanhamento).should be_a_new(Acompanhamento)
    end
  end

  describe "GET edit" do
    it "assigns the requested acompanhamento as @acompanhamento" do
      acompanhamento = Acompanhamento.create! valid_attributes
      get :edit, {:id => acompanhamento.to_param}, valid_session
      assigns(:acompanhamento).should eq(acompanhamento)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Acompanhamento" do
        expect {
          post :create, {:acompanhamento => valid_attributes}, valid_session
        }.to change(Acompanhamento, :count).by(1)
      end

      it "assigns a newly created acompanhamento as @acompanhamento" do
        post :create, {:acompanhamento => valid_attributes}, valid_session
        assigns(:acompanhamento).should be_a(Acompanhamento)
        assigns(:acompanhamento).should be_persisted
      end

      it "redirects to the created acompanhamento" do
        post :create, {:acompanhamento => valid_attributes}, valid_session
        response.should redirect_to(Acompanhamento.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved acompanhamento as @acompanhamento" do
        # Trigger the behavior that occurs when invalid params are submitted
        Acompanhamento.any_instance.stub(:save).and_return(false)
        post :create, {:acompanhamento => { "contratos" => "invalid value" }}, valid_session
        assigns(:acompanhamento).should be_a_new(Acompanhamento)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Acompanhamento.any_instance.stub(:save).and_return(false)
        post :create, {:acompanhamento => { "contratos" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested acompanhamento" do
        acompanhamento = Acompanhamento.create! valid_attributes
        # Assuming there are no other acompanhamentos in the database, this
        # specifies that the Acompanhamento created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Acompanhamento.any_instance.should_receive(:update_attributes).with({ "contratos" => "" })
        put :update, {:id => acompanhamento.to_param, :acompanhamento => { "contratos" => "" }}, valid_session
      end

      it "assigns the requested acompanhamento as @acompanhamento" do
        acompanhamento = Acompanhamento.create! valid_attributes
        put :update, {:id => acompanhamento.to_param, :acompanhamento => valid_attributes}, valid_session
        assigns(:acompanhamento).should eq(acompanhamento)
      end

      it "redirects to the acompanhamento" do
        acompanhamento = Acompanhamento.create! valid_attributes
        put :update, {:id => acompanhamento.to_param, :acompanhamento => valid_attributes}, valid_session
        response.should redirect_to(acompanhamento)
      end
    end

    describe "with invalid params" do
      it "assigns the acompanhamento as @acompanhamento" do
        acompanhamento = Acompanhamento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Acompanhamento.any_instance.stub(:save).and_return(false)
        put :update, {:id => acompanhamento.to_param, :acompanhamento => { "contratos" => "invalid value" }}, valid_session
        assigns(:acompanhamento).should eq(acompanhamento)
      end

      it "re-renders the 'edit' template" do
        acompanhamento = Acompanhamento.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Acompanhamento.any_instance.stub(:save).and_return(false)
        put :update, {:id => acompanhamento.to_param, :acompanhamento => { "contratos" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested acompanhamento" do
      acompanhamento = Acompanhamento.create! valid_attributes
      expect {
        delete :destroy, {:id => acompanhamento.to_param}, valid_session
      }.to change(Acompanhamento, :count).by(-1)
    end

    it "redirects to the acompanhamentos list" do
      acompanhamento = Acompanhamento.create! valid_attributes
      delete :destroy, {:id => acompanhamento.to_param}, valid_session
      response.should redirect_to(acompanhamentos_url)
    end
  end

end
