require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AssuntoProcessualsController do

  # This should return the minimal set of attributes required to create a valid
  # AssuntoProcessual. As you add validations to AssuntoProcessual, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AssuntoProcessualsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all assunto_processuals as @assunto_processuals" do
      assunto_processual = AssuntoProcessual.create! valid_attributes
      get :index, {}, valid_session
      assigns(:assunto_processuals).should eq([assunto_processual])
    end
  end

  describe "GET show" do
    it "assigns the requested assunto_processual as @assunto_processual" do
      assunto_processual = AssuntoProcessual.create! valid_attributes
      get :show, {:id => assunto_processual.to_param}, valid_session
      assigns(:assunto_processual).should eq(assunto_processual)
    end
  end

  describe "GET new" do
    it "assigns a new assunto_processual as @assunto_processual" do
      get :new, {}, valid_session
      assigns(:assunto_processual).should be_a_new(AssuntoProcessual)
    end
  end

  describe "GET edit" do
    it "assigns the requested assunto_processual as @assunto_processual" do
      assunto_processual = AssuntoProcessual.create! valid_attributes
      get :edit, {:id => assunto_processual.to_param}, valid_session
      assigns(:assunto_processual).should eq(assunto_processual)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AssuntoProcessual" do
        expect {
          post :create, {:assunto_processual => valid_attributes}, valid_session
        }.to change(AssuntoProcessual, :count).by(1)
      end

      it "assigns a newly created assunto_processual as @assunto_processual" do
        post :create, {:assunto_processual => valid_attributes}, valid_session
        assigns(:assunto_processual).should be_a(AssuntoProcessual)
        assigns(:assunto_processual).should be_persisted
      end

      it "redirects to the created assunto_processual" do
        post :create, {:assunto_processual => valid_attributes}, valid_session
        response.should redirect_to(AssuntoProcessual.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved assunto_processual as @assunto_processual" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssuntoProcessual.any_instance.stub(:save).and_return(false)
        post :create, {:assunto_processual => { "name" => "invalid value" }}, valid_session
        assigns(:assunto_processual).should be_a_new(AssuntoProcessual)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AssuntoProcessual.any_instance.stub(:save).and_return(false)
        post :create, {:assunto_processual => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested assunto_processual" do
        assunto_processual = AssuntoProcessual.create! valid_attributes
        # Assuming there are no other assunto_processuals in the database, this
        # specifies that the AssuntoProcessual created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AssuntoProcessual.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => assunto_processual.to_param, :assunto_processual => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested assunto_processual as @assunto_processual" do
        assunto_processual = AssuntoProcessual.create! valid_attributes
        put :update, {:id => assunto_processual.to_param, :assunto_processual => valid_attributes}, valid_session
        assigns(:assunto_processual).should eq(assunto_processual)
      end

      it "redirects to the assunto_processual" do
        assunto_processual = AssuntoProcessual.create! valid_attributes
        put :update, {:id => assunto_processual.to_param, :assunto_processual => valid_attributes}, valid_session
        response.should redirect_to(assunto_processual)
      end
    end

    describe "with invalid params" do
      it "assigns the assunto_processual as @assunto_processual" do
        assunto_processual = AssuntoProcessual.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssuntoProcessual.any_instance.stub(:save).and_return(false)
        put :update, {:id => assunto_processual.to_param, :assunto_processual => { "name" => "invalid value" }}, valid_session
        assigns(:assunto_processual).should eq(assunto_processual)
      end

      it "re-renders the 'edit' template" do
        assunto_processual = AssuntoProcessual.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AssuntoProcessual.any_instance.stub(:save).and_return(false)
        put :update, {:id => assunto_processual.to_param, :assunto_processual => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested assunto_processual" do
      assunto_processual = AssuntoProcessual.create! valid_attributes
      expect {
        delete :destroy, {:id => assunto_processual.to_param}, valid_session
      }.to change(AssuntoProcessual, :count).by(-1)
    end

    it "redirects to the assunto_processuals list" do
      assunto_processual = AssuntoProcessual.create! valid_attributes
      delete :destroy, {:id => assunto_processual.to_param}, valid_session
      response.should redirect_to(assunto_processuals_url)
    end
  end

end
