require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CentroCustosController do

  # This should return the minimal set of attributes required to create a valid
  # CentroCusto. As you add validations to CentroCusto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CentroCustosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all centro_custos as @centro_custos" do
      centro_custo = CentroCusto.create! valid_attributes
      get :index, {}, valid_session
      assigns(:centro_custos).should eq([centro_custo])
    end
  end

  describe "GET show" do
    it "assigns the requested centro_custo as @centro_custo" do
      centro_custo = CentroCusto.create! valid_attributes
      get :show, {:id => centro_custo.to_param}, valid_session
      assigns(:centro_custo).should eq(centro_custo)
    end
  end

  describe "GET new" do
    it "assigns a new centro_custo as @centro_custo" do
      get :new, {}, valid_session
      assigns(:centro_custo).should be_a_new(CentroCusto)
    end
  end

  describe "GET edit" do
    it "assigns the requested centro_custo as @centro_custo" do
      centro_custo = CentroCusto.create! valid_attributes
      get :edit, {:id => centro_custo.to_param}, valid_session
      assigns(:centro_custo).should eq(centro_custo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CentroCusto" do
        expect {
          post :create, {:centro_custo => valid_attributes}, valid_session
        }.to change(CentroCusto, :count).by(1)
      end

      it "assigns a newly created centro_custo as @centro_custo" do
        post :create, {:centro_custo => valid_attributes}, valid_session
        assigns(:centro_custo).should be_a(CentroCusto)
        assigns(:centro_custo).should be_persisted
      end

      it "redirects to the created centro_custo" do
        post :create, {:centro_custo => valid_attributes}, valid_session
        response.should redirect_to(CentroCusto.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved centro_custo as @centro_custo" do
        # Trigger the behavior that occurs when invalid params are submitted
        CentroCusto.any_instance.stub(:save).and_return(false)
        post :create, {:centro_custo => { "name" => "invalid value" }}, valid_session
        assigns(:centro_custo).should be_a_new(CentroCusto)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CentroCusto.any_instance.stub(:save).and_return(false)
        post :create, {:centro_custo => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested centro_custo" do
        centro_custo = CentroCusto.create! valid_attributes
        # Assuming there are no other centro_custos in the database, this
        # specifies that the CentroCusto created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CentroCusto.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => centro_custo.to_param, :centro_custo => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested centro_custo as @centro_custo" do
        centro_custo = CentroCusto.create! valid_attributes
        put :update, {:id => centro_custo.to_param, :centro_custo => valid_attributes}, valid_session
        assigns(:centro_custo).should eq(centro_custo)
      end

      it "redirects to the centro_custo" do
        centro_custo = CentroCusto.create! valid_attributes
        put :update, {:id => centro_custo.to_param, :centro_custo => valid_attributes}, valid_session
        response.should redirect_to(centro_custo)
      end
    end

    describe "with invalid params" do
      it "assigns the centro_custo as @centro_custo" do
        centro_custo = CentroCusto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CentroCusto.any_instance.stub(:save).and_return(false)
        put :update, {:id => centro_custo.to_param, :centro_custo => { "name" => "invalid value" }}, valid_session
        assigns(:centro_custo).should eq(centro_custo)
      end

      it "re-renders the 'edit' template" do
        centro_custo = CentroCusto.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CentroCusto.any_instance.stub(:save).and_return(false)
        put :update, {:id => centro_custo.to_param, :centro_custo => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested centro_custo" do
      centro_custo = CentroCusto.create! valid_attributes
      expect {
        delete :destroy, {:id => centro_custo.to_param}, valid_session
      }.to change(CentroCusto, :count).by(-1)
    end

    it "redirects to the centro_custos list" do
      centro_custo = CentroCusto.create! valid_attributes
      delete :destroy, {:id => centro_custo.to_param}, valid_session
      response.should redirect_to(centro_custos_url)
    end
  end

end
