require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProcessosController do

  # This should return the minimal set of attributes required to create a valid
  # Processo. As you add validations to Processo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "numero" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProcessosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all processos as @processos" do
      processo = Processo.create! valid_attributes
      get :index, {}, valid_session
      assigns(:processos).should eq([processo])
    end
  end

  describe "GET show" do
    it "assigns the requested processo as @processo" do
      processo = Processo.create! valid_attributes
      get :show, {:id => processo.to_param}, valid_session
      assigns(:processo).should eq(processo)
    end
  end

  describe "GET new" do
    it "assigns a new processo as @processo" do
      get :new, {}, valid_session
      assigns(:processo).should be_a_new(Processo)
    end
  end

  describe "GET edit" do
    it "assigns the requested processo as @processo" do
      processo = Processo.create! valid_attributes
      get :edit, {:id => processo.to_param}, valid_session
      assigns(:processo).should eq(processo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Processo" do
        expect {
          post :create, {:processo => valid_attributes}, valid_session
        }.to change(Processo, :count).by(1)
      end

      it "assigns a newly created processo as @processo" do
        post :create, {:processo => valid_attributes}, valid_session
        assigns(:processo).should be_a(Processo)
        assigns(:processo).should be_persisted
      end

      it "redirects to the created processo" do
        post :create, {:processo => valid_attributes}, valid_session
        response.should redirect_to(Processo.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved processo as @processo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Processo.any_instance.stub(:save).and_return(false)
        post :create, {:processo => { "numero" => "invalid value" }}, valid_session
        assigns(:processo).should be_a_new(Processo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Processo.any_instance.stub(:save).and_return(false)
        post :create, {:processo => { "numero" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested processo" do
        processo = Processo.create! valid_attributes
        # Assuming there are no other processos in the database, this
        # specifies that the Processo created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Processo.any_instance.should_receive(:update_attributes).with({ "numero" => "MyString" })
        put :update, {:id => processo.to_param, :processo => { "numero" => "MyString" }}, valid_session
      end

      it "assigns the requested processo as @processo" do
        processo = Processo.create! valid_attributes
        put :update, {:id => processo.to_param, :processo => valid_attributes}, valid_session
        assigns(:processo).should eq(processo)
      end

      it "redirects to the processo" do
        processo = Processo.create! valid_attributes
        put :update, {:id => processo.to_param, :processo => valid_attributes}, valid_session
        response.should redirect_to(processo)
      end
    end

    describe "with invalid params" do
      it "assigns the processo as @processo" do
        processo = Processo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Processo.any_instance.stub(:save).and_return(false)
        put :update, {:id => processo.to_param, :processo => { "numero" => "invalid value" }}, valid_session
        assigns(:processo).should eq(processo)
      end

      it "re-renders the 'edit' template" do
        processo = Processo.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Processo.any_instance.stub(:save).and_return(false)
        put :update, {:id => processo.to_param, :processo => { "numero" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested processo" do
      processo = Processo.create! valid_attributes
      expect {
        delete :destroy, {:id => processo.to_param}, valid_session
      }.to change(Processo, :count).by(-1)
    end

    it "redirects to the processos list" do
      processo = Processo.create! valid_attributes
      delete :destroy, {:id => processo.to_param}, valid_session
      response.should redirect_to(processos_url)
    end
  end

end
