require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RiscosController do

  # This should return the minimal set of attributes required to create a valid
  # Risco. As you add validations to Risco, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RiscosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all riscos as @riscos" do
      risco = Risco.create! valid_attributes
      get :index, {}, valid_session
      assigns(:riscos).should eq([risco])
    end
  end

  describe "GET show" do
    it "assigns the requested risco as @risco" do
      risco = Risco.create! valid_attributes
      get :show, {:id => risco.to_param}, valid_session
      assigns(:risco).should eq(risco)
    end
  end

  describe "GET new" do
    it "assigns a new risco as @risco" do
      get :new, {}, valid_session
      assigns(:risco).should be_a_new(Risco)
    end
  end

  describe "GET edit" do
    it "assigns the requested risco as @risco" do
      risco = Risco.create! valid_attributes
      get :edit, {:id => risco.to_param}, valid_session
      assigns(:risco).should eq(risco)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Risco" do
        expect {
          post :create, {:risco => valid_attributes}, valid_session
        }.to change(Risco, :count).by(1)
      end

      it "assigns a newly created risco as @risco" do
        post :create, {:risco => valid_attributes}, valid_session
        assigns(:risco).should be_a(Risco)
        assigns(:risco).should be_persisted
      end

      it "redirects to the created risco" do
        post :create, {:risco => valid_attributes}, valid_session
        response.should redirect_to(Risco.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved risco as @risco" do
        # Trigger the behavior that occurs when invalid params are submitted
        Risco.any_instance.stub(:save).and_return(false)
        post :create, {:risco => { "name" => "invalid value" }}, valid_session
        assigns(:risco).should be_a_new(Risco)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Risco.any_instance.stub(:save).and_return(false)
        post :create, {:risco => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested risco" do
        risco = Risco.create! valid_attributes
        # Assuming there are no other riscos in the database, this
        # specifies that the Risco created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Risco.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => risco.to_param, :risco => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested risco as @risco" do
        risco = Risco.create! valid_attributes
        put :update, {:id => risco.to_param, :risco => valid_attributes}, valid_session
        assigns(:risco).should eq(risco)
      end

      it "redirects to the risco" do
        risco = Risco.create! valid_attributes
        put :update, {:id => risco.to_param, :risco => valid_attributes}, valid_session
        response.should redirect_to(risco)
      end
    end

    describe "with invalid params" do
      it "assigns the risco as @risco" do
        risco = Risco.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Risco.any_instance.stub(:save).and_return(false)
        put :update, {:id => risco.to_param, :risco => { "name" => "invalid value" }}, valid_session
        assigns(:risco).should eq(risco)
      end

      it "re-renders the 'edit' template" do
        risco = Risco.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Risco.any_instance.stub(:save).and_return(false)
        put :update, {:id => risco.to_param, :risco => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested risco" do
      risco = Risco.create! valid_attributes
      expect {
        delete :destroy, {:id => risco.to_param}, valid_session
      }.to change(Risco, :count).by(-1)
    end

    it "redirects to the riscos list" do
      risco = Risco.create! valid_attributes
      delete :destroy, {:id => risco.to_param}, valid_session
      response.should redirect_to(riscos_url)
    end
  end

end
